"""Build a case-scoped unified-evaluation identity map from the local Docker seed database.

The v2 benchmark has synthetic users and members.  This command maps those
namespaces to the disposable local demo user and members so the real graph can
be exercised without treating synthetic cases as real patients.

The output is intentionally written below ``var/`` and is ignored by Git.
No API key, raw medical payload, or production identifier is written to a
tracked file.  Provider and RAG sources are generated by each shadow run and
are therefore not placed in ``source_ids``.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
import sys
from typing import Any

from sqlalchemy import select


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "backend"))

from app.agent.unified_eval_dataset import load_unified_agent_benchmark  # noqa: E402
from app.core.database import SessionLocal  # noqa: E402
from app.models import (  # noqa: E402
    FamilyMember,
    HealthProfile,
    HealthRecordEvent,
    MedicalDocument,
    User,
)


def _single_user(session, requested_user_id: str | None) -> User:
    if requested_user_id:
        user = session.get(User, requested_user_id)
        if user is None:
            raise ValueError(f"local user was not found: {requested_user_id}")
        return user
    users = list(session.scalars(select(User).order_by(User.created_at, User.id)))
    if len(users) != 1:
        raise ValueError(
            "expected exactly one local demo user; pass --user-id to choose one"
        )
    return users[0]


def _source_for_member(items: list[Any], member_id: str) -> str | None:
    matches = [item.source_id for item in items if item.member_id == member_id]
    return matches[0] if matches else None


def build_local_identity_map(
    *, session, project_root: Path = PROJECT_ROOT, user_id: str | None = None
) -> dict[str, Any]:
    """Create a deterministic case map and report local data coverage."""

    worlds, _, manifest = load_unified_agent_benchmark(project_root=project_root)
    user = _single_user(session, user_id)
    members = list(
        session.scalars(
            select(FamilyMember).where(FamilyMember.user_id == str(user.id))
        )
    )
    members_by_relationship = {member.relationship: member for member in members}
    profiles = {
        profile.member_id: profile
        for profile in session.scalars(select(HealthProfile)).all()
        if profile.member_id in {member.id for member in members}
    }
    records_by_member: dict[str, list[HealthRecordEvent]] = {}
    for record in session.scalars(
        select(HealthRecordEvent).where(HealthRecordEvent.user_id == str(user.id))
    ):
        records_by_member.setdefault(record.member_id, []).append(record)
    documents_by_member: dict[str, list[MedicalDocument]] = {}
    for document in session.scalars(
        select(MedicalDocument).where(MedicalDocument.user_id == str(user.id))
    ):
        documents_by_member.setdefault(document.member_id, []).append(document)

    cases: dict[str, dict[str, Any]] = {}
    missing_relationships: Counter[str] = Counter()
    missing_profiles: Counter[str] = Counter()
    missing_records: Counter[str] = Counter()
    mapped_source_count = 0

    for world in worlds.world_states:
        benchmark_to_actual_member: dict[str, str] = {}
        for benchmark_member in world.members:
            local_member = members_by_relationship.get(benchmark_member.relationship)
            if local_member is None:
                missing_relationships[benchmark_member.relationship] += 1
                continue
            benchmark_to_actual_member[benchmark_member.member_id] = str(local_member.id)

        source_ids: dict[str, str] = {}
        for benchmark_member in world.members:
            actual_member_id = benchmark_to_actual_member.get(benchmark_member.member_id)
            if actual_member_id is None:
                continue
            profile = profiles.get(actual_member_id)
            if profile is None:
                missing_profiles[benchmark_member.relationship] += 1
            else:
                source_ids[f"health_profile:{profile.id}"] = benchmark_member.profile_source_id

        for item in (*world.prescriptions, *world.medicine_box):
            actual_member_id = benchmark_to_actual_member.get(item.member_id)
            if actual_member_id is None:
                continue
            prefix = (
                "prescriptions"
                if item.source_id.split(":source:")[-1].startswith("prescription")
                else "medicine_box"
            )
            source_ids[f"{prefix}:{actual_member_id}"] = item.source_id

        for item in world.health_records:
            actual_member_id = benchmark_to_actual_member.get(item.member_id)
            if actual_member_id is None:
                continue
            local_records = records_by_member.get(actual_member_id, [])
            local_documents = documents_by_member.get(actual_member_id, [])
            if not local_records:
                missing_records[world.world_state_id] += 1
            for record in local_records[:1]:
                source_ids[f"health_record_event:{record.id}"] = item.source_id
            for document in local_documents[:1]:
                source_ids[
                    f"medical-document:{document.id}:{document.document_version}"
                ] = item.source_id

        mapped_source_count += len(source_ids)
        cases[world.world_state_id] = {
            "benchmark_user_id": world.user.user_id,
            "actual_user_id": str(user.id),
            "member_ids": benchmark_to_actual_member,
            "source_ids": source_ids,
        }

    return {
        "schema_version": "unified-agent-identity-map-v1",
        "benchmark_dataset_version": manifest.dataset_version,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "local_demo_scope": {
            "user_id": str(user.id),
            "member_count": len(members),
            "member_relationships": sorted(members_by_relationship),
            "synthetic_worlds_are_not_patients": True,
        },
        "coverage": {
            "case_count": len(cases),
            "mapped_source_count": mapped_source_count,
            "missing_relationships": dict(missing_relationships),
            "missing_profiles": dict(missing_profiles),
            "worlds_with_missing_local_records": len(missing_records),
        },
        "cases": cases,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--user-id", default=None)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("var/demo/unified_agent_identity_map.local.json"),
    )
    args = parser.parse_args()

    payload = build_local_identity_map(session=SessionLocal(), user_id=args.user_id)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"output: {args.output}")
    print(f"cases: {payload['coverage']['case_count']}")
    print(f"mapped_sources: {payload['coverage']['mapped_source_count']}")
    print(
        "missing_local_records: "
        f"{payload['coverage']['worlds_with_missing_local_records']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
