"""Agent workflow and harness contract package."""

from app.agent.ablation_schemas import (
    AblationCaseResult,
    AblationHarnessOutput,
    AblationRunTrace,
    AblationToolCallTrace,
    BusinessHarnessCase,
    ExpectedToolInvocation,
    FairnessConfig,
    SliceMetrics,
    StrategyMetrics,
)
from app.agent.context_schemas import (
    ConfirmedFact,
    ContextEnvelope,
    ConversationSummary,
    MemoryRef,
    RAGSourceRef,
    RoleSpecificContextView,
    RunSummary,
    TaskState,
    ToolEvidenceRef,
)
from app.agent.model_gateway import (
    DeterministicModelProvider,
    ModelGateway,
    ModelProvider,
    OpenAICompatibleModelProvider,
    create_model_gateway,
)
from app.agent.model_gateway_schemas import (
    ModelCallRequest,
    ModelCallResult,
    ModelCallTrace,
    ModelMessage,
    ModelProviderAttemptTrace,
)
from app.agent.eval_schemas import EvaluationResult, ExpectedCase, ExpectedSource
from app.agent.evaluator import DeterministicEvaluator
from app.agent.harness_runtime import (
    AgentHarnessRuntime,
    HarnessRuntimeBatchResult,
    HarnessRuntimeResult,
)
from app.agent.context_manager import ContextManager, ResetContextState
from app.agent.safety_confirmation import (
    ConfirmationAction,
    ConfirmationScope,
    ConfirmationState,
    ConfirmationStateMachine,
    ConfirmationTransitionRequest,
    ConfirmationTransitionResult,
    FinalOutputSafetyResult,
    ThreeLayerSafetyGuard,
    build_confirmation_scope,
)
from app.agent.complexity_router import DeterministicComplexityRouter
from app.agent.domain_agents import (
    DomainAgent,
    DomainAgentInput,
    MedicationAgent,
    ReportAgent,
    TriageAgent,
    allowed_tools_for_role,
    build_domain_agent_registry,
)
from app.agent.orchestration import (
    BoundedSupervisor,
    DeterministicBoundedSupervisor,
    DeterministicTaskPlanner,
    TaskPlanner,
)
from app.agent.orchestration_schemas import (
    AgentTaskResult,
    ComplexityRoute,
    ComplexityRoutingRequest,
    DomainAgentRole,
    OrchestrationRunResult,
    PlanStep,
    SafetyDecision,
    SafetyDecisionBundle,
    SafetyStage,
    SupervisorDecision,
    TaskPlan,
)
from app.agent.run_trace_schemas import (
    FinalAnswerTrace,
    ObservationTrace,
    RAGTrace,
    RunTrace,
    SafetyTrace,
    ToolCallTrace,
)
from app.agent.runtime_schemas import PersistedRunArtifacts, RuntimeRequestContext
from app.agent.workflow_schemas import (
    WorkflowFinalAnswerDraft,
    WorkflowPlan,
    WorkflowResumeContext,
    WorkflowRunRequest,
    WorkflowRunResult,
)

__all__ = [
    "AblationCaseResult",
    "AblationHarnessOutput",
    "AblationRunTrace",
    "AblationToolCallTrace",
    "BusinessHarnessCase",
    "ConfirmedFact",
    "ContextEnvelope",
    "ContextManager",
    "ConfirmationScope",
    "ConfirmationAction",
    "ConfirmationState",
    "ConfirmationStateMachine",
    "ConfirmationTransitionRequest",
    "ConfirmationTransitionResult",
    "ComplexityRoute",
    "ComplexityRoutingRequest",
    "DeterministicComplexityRouter",
    "DeterministicBoundedSupervisor",
    "DeterministicTaskPlanner",
    "DomainAgent",
    "DomainAgentInput",
    "DomainAgentRole",
    "ConversationSummary",
    "DeterministicEvaluator",
    "EvaluationResult",
    "ExpectedCase",
    "ExpectedSource",
    "ExpectedToolInvocation",
    "FairnessConfig",
    "FinalAnswerTrace",
    "FinalOutputSafetyResult",
    "AgentHarnessRuntime",
    "HarnessRuntimeBatchResult",
    "HarnessRuntimeResult",
    "MemoryRef",
    "MedicationAgent",
    "DeterministicModelProvider",
    "ModelCallRequest",
    "ModelCallResult",
    "ModelCallTrace",
    "ModelGateway",
    "ModelMessage",
    "ModelProvider",
    "ModelProviderAttemptTrace",
    "OpenAICompatibleModelProvider",
    "ObservationTrace",
    "RAGSourceRef",
    "ReportAgent",
    "RAGTrace",
    "PersistedRunArtifacts",
    "ResetContextState",
    "RoleSpecificContextView",
    "PlanStep",
    "RunTrace",
    "RunSummary",
    "SafetyTrace",
    "SliceMetrics",
    "StrategyMetrics",
    "SafetyDecisionBundle",
    "SafetyDecision",
    "ThreeLayerSafetyGuard",
    "SafetyStage",
    "SupervisorDecision",
    "TaskPlanner",
    "TaskState",
    "TaskPlan",
    "AgentTaskResult",
    "TriageAgent",
    "ToolEvidenceRef",
    "ToolCallTrace",
    "WorkflowFinalAnswerDraft",
    "WorkflowPlan",
    "WorkflowResumeContext",
    "WorkflowRunRequest",
    "WorkflowRunResult",
    "RuntimeRequestContext",
    "create_model_gateway",
    "BoundedSupervisor",
    "OrchestrationRunResult",
    "allowed_tools_for_role",
    "build_domain_agent_registry",
    "build_confirmation_scope",
]
