from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

import httpx
from pydantic import Field

from app.agent.context_schemas import ContractModel, FinalStatus
from app.agent.runtime_harness import (
    RuntimeE2EHarnessRunner,
    RuntimeHarnessOutput,
    RuntimeHarnessSuite,
)


DEMO_CASE_LABELS = {
    "3d_demo_refill_father": "父亲降压药续方",
    "3d_demo_consultation_mother": "母亲中医复诊材料",
    "3d_demo_reminder_mother": "母亲用药提醒草稿",
    "3d_demo_high_risk_blocked": "高风险加量请求拦截",
}
EXPECTED_DEMO_CASE_IDS = tuple(DEMO_CASE_LABELS)


class DemoScenarioSummary(ContractModel):
    case_id: str
    label: str
    initial_status: FinalStatus
    final_status: FinalStatus
    continued: bool
    source_count: int = Field(ge=0)
    external_action_status: str
    passed: bool
    failure_reasons: tuple[str, ...] = Field(default_factory=tuple)


class MvpDemoReport(ContractModel):
    report_kind: Literal["local_mvp_demo"] = "local_mvp_demo"
    environment: str
    generated_at: datetime
    run_key_prefix: str
    scenarios: tuple[DemoScenarioSummary, ...]
    scenario_pass_rate: float = Field(ge=0.0, le=1.0)
    all_passed: bool


class MvpDemoError(RuntimeError):
    pass


class MvpDemoRunner:
    @staticmethod
    def load_suite(path: Path) -> RuntimeHarnessSuite:
        suite = RuntimeE2EHarnessRunner.load_suite(path)
        MvpDemoRunner.validate_suite(suite)
        return suite

    @staticmethod
    def validate_suite(suite: RuntimeHarnessSuite) -> None:
        case_ids = tuple(case.case_id for case in suite.trace_cases)
        if case_ids != EXPECTED_DEMO_CASE_IDS:
            raise MvpDemoError(
                "demo suite must contain the four fixed scenarios in presentation order"
            )
        if suite.guard_cases:
            raise MvpDemoError("demo suite must not contain API guard cases")

    @staticmethod
    def build_report(output: RuntimeHarnessOutput) -> MvpDemoReport:
        result_ids = tuple(item.case_id for item in output.trace_results)
        if result_ids != EXPECTED_DEMO_CASE_IDS or output.guard_results:
            raise MvpDemoError("runtime output does not match the fixed demo suite")

        scenarios = []
        for result in output.trace_results:
            passed = (
                result.runtime_contract_passed
                and result.evaluation.task_success
                and result.external_action_status == "not_submitted"
            )
            scenarios.append(
                DemoScenarioSummary(
                    case_id=result.case_id,
                    label=DEMO_CASE_LABELS[result.case_id],
                    initial_status=result.initial_status,
                    final_status=result.final_status,
                    continued=result.continued,
                    source_count=len(result.source_ids),
                    external_action_status=result.external_action_status,
                    passed=passed,
                    failure_reasons=result.evaluation.failure_reasons,
                )
            )

        pass_count = sum(item.passed for item in scenarios)
        return MvpDemoReport(
            environment=output.environment,
            generated_at=output.generated_at,
            run_key_prefix=output.run_key_prefix,
            scenarios=tuple(scenarios),
            scenario_pass_rate=pass_count / len(scenarios),
            all_passed=pass_count == len(scenarios),
        )

    @staticmethod
    def render_console(report: MvpDemoReport) -> str:
        lines = ["Family Health Agent MVP - fixed four-scenario demo", ""]
        for index, scenario in enumerate(report.scenarios, start=1):
            marker = "PASS" if scenario.passed else "FAIL"
            flow = f"{scenario.initial_status} -> {scenario.final_status}"
            lines.append(
                f"[{marker}] {index}. {scenario.label}: {flow}; "
                f"sources={scenario.source_count}; external={scenario.external_action_status}"
            )
            if scenario.failure_reasons:
                lines.append("       failures=" + ", ".join(scenario.failure_reasons))
        lines.extend(
            [
                "",
                f"Result: {sum(item.passed for item in report.scenarios)}/"
                f"{len(report.scenarios)} scenarios passed.",
                "This is a local deterministic demo, not a clinical or production claim.",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def render_markdown(report: MvpDemoReport) -> str:
        lines = [
            "# 3D MVP Demo Verification Report",
            "",
            "> Generated by the fixed local deterministic demo. This is not a production, clinical, or real-LLM quality claim.",
            "",
            f"- Environment: `{report.environment}`",
            f"- Generated at: `{report.generated_at.isoformat()}`",
            f"- Scenario pass rate: `{report.scenario_pass_rate:.4f}`",
            "- External action contract: `not_submitted`",
            "",
            "| Scenario | Initial status | Final status | Continued | Sources | External action | Passed | Failures |",
            "| --- | --- | --- | --- | ---: | --- | --- | --- |",
        ]
        for scenario in report.scenarios:
            failures = ", ".join(scenario.failure_reasons) or "-"
            lines.append(
                f"| {scenario.label} | {scenario.initial_status} | "
                f"{scenario.final_status} | {str(scenario.continued).lower()} | "
                f"{scenario.source_count} | {scenario.external_action_status} | "
                f"{str(scenario.passed).lower()} | {failures} |"
            )
        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def write_reports(
        report: MvpDemoReport,
        *,
        json_path: Path,
        markdown_path: Path,
    ) -> None:
        json_path.parent.mkdir(parents=True, exist_ok=True)
        markdown_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(
            json.dumps(report.model_dump(mode="json"), ensure_ascii=False, indent=2)
            + "\n",
            encoding="utf-8",
        )
        markdown_path.write_text(
            MvpDemoRunner.render_markdown(report),
            encoding="utf-8",
        )


def _default_report_paths(root: Path) -> tuple[Path, Path]:
    return root / "var" / "demo" / "mvp-demo.json", root / "var" / "demo" / "mvp-demo.md"


def main() -> None:
    root = Path(__file__).resolve().parents[3]
    default_json, default_markdown = _default_report_paths(root)
    parser = argparse.ArgumentParser(
        description="Run the fixed four-scenario MVP demo against a live Runtime API"
    )
    parser.add_argument("--base-url", default="http://localhost:8000")
    parser.add_argument(
        "--suite",
        type=Path,
        default=Path(__file__).with_name("demo_scenarios.json"),
    )
    parser.add_argument("--json-report", type=Path, default=default_json)
    parser.add_argument("--markdown-report", type=Path, default=default_markdown)
    parser.add_argument(
        "--environment",
        default="local_docker_postgresql_deterministic",
    )
    parser.add_argument(
        "--run-key-prefix",
        default=f"3d-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
    )
    args = parser.parse_args()

    suite = MvpDemoRunner.load_suite(args.suite)
    with httpx.Client(base_url=args.base_url, timeout=60.0) as client:
        output = RuntimeE2EHarnessRunner(
            client,
            run_key_prefix=args.run_key_prefix,
            environment=args.environment,
        ).run(suite)
    report = MvpDemoRunner.build_report(output)
    MvpDemoRunner.write_reports(
        report,
        json_path=args.json_report,
        markdown_path=args.markdown_report,
    )
    print(MvpDemoRunner.render_console(report))
    if not report.all_passed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()


__all__ = [
    "DemoScenarioSummary",
    "EXPECTED_DEMO_CASE_IDS",
    "MvpDemoError",
    "MvpDemoReport",
    "MvpDemoRunner",
]
